---
  version: 1
  schedule:
    type: "simple"
    interval: "5s"
  max-failures: 10
  workflow:
    collect:
      metrics:
        /intel/procfs/cpu/*/utilization_percentage: {}
      process:
        - plugin_name: "threshold"
          config:
            /intel/procfs/cpu/*/utilization_percentage : 95
          publish:
            - plugin_name: "file"
              config:
                file: "/tmp/cpu_threshold.log"
